### ISSUE TITLE
using "with" in query stop us from chaining the query.

### ISSUE THREAD

**Issue by rasmusebbesen** [nodes-php/database#5]
Chaining query builder using "with()" prevents us from using certain nodes repository specific methods

```
$ship = $this->starCodeRepository->with('star')->getByOrFail('star_code', $shipStarCode);
```

```
{
  "message": "Call to undefined method Illuminate\Database\Query\Builder::getByOrFail()",
  "code": 500,
  "debug": {
    "class": "BadMethodCallException",
    "file": "/var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
    "line": 2161,
    "trace": [
      "#0 [internal function]: Illuminate\Database\Query\Builder->__call('getByOrFail', Array)",
      "#1 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1247): call_user_func_array(Array, Array)",
      "#2 /var/www/dfds/htdocs/project/Controllers/Api/ActivitiesController.php(71): Illuminate\Database\Eloquent\Builder->__call('getByOrFail', Array)",
      "#3 [internal function]: DFDS\Controllers\Api\ActivitiesController->feed('PEARL SEAWAYS')",
      "#4 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(76): call_user_func_array(Array, Array)",
      "#5 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('feed', Array)",
      "#6 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(DFDS\Controllers\Api\ActivitiesController), Object(Illuminate\Routing\Route), 'feed')",
      "#7 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))",
      "#8 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#9 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))",
      "#10 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#11 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#12 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(DFDS\Controllers\Api\ActivitiesController), Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request), 'feed')",
      "#13 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request), 'DFDS\\Controller...', 'feed')",
      "#14 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Dingo\Api\Http\Request))",
      "#15 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Route->run(Object(Dingo\Api\Http\Request))",
      "#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))",
      "#17 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#18 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))",
      "#19 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#20 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#21 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request))",
      "#22 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(654): Illuminate\Routing\Router->dispatchToRoute(Object(Dingo\Api\Http\Request))",
      "#23 /var/www/dfds/htdocs/vendor/dingo/api/src/Routing/Adapter/Laravel.php(65): Illuminate\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))",
      "#24 /var/www/dfds/htdocs/vendor/dingo/api/src/Routing/Router.php(559): Dingo\Api\Routing\Adapter\Laravel->dispatch(Object(Dingo\Api\Http\Request), 'v1')",
      "#25 /var/www/dfds/htdocs/vendor/dingo/api/src/Http/Middleware/Request.php(110): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))",
      "#26 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))",
      "#27 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#28 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(64): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#29 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#30 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#31 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#32 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#33 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#34 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#35 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#36 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#37 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#38 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#39 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#40 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#41 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#42 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#43 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#44 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#45 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#46 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#47 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#48 /var/www/dfds/htdocs/vendor/dingo/api/src/Http/Middleware/Request.php(111): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#49 /var/www/dfds/htdocs/vendor/dingo/api/src/Http/Middleware/Request.php(89): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))",
      "#50 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Dingo\Api\Http\Request), Object(Closure))",
      "#51 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#52 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))",
      "#53 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))",
      "#54 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))",
      "#55 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))",
      "#56 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#57 /var/www/dfds/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))",
      "#58 /var/www/dfds/htdocs/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))",
      "#59 {main}"
    ]
  }
}
```

**Comment by rugaard** [comment]
Fixed in release 0.1.5.
